'use client'
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react"
import { AuthContextProvider } from "@/context/AuthContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Alra the AI Advisor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
        {children}
        <Analytics />
        </AuthContextProvider>
        </body>
    </html>
  );
}
